version: '3.8'
services:
  scoring:
    build:
      context: ./score_service
    ports:
      - "50051:50051"
    networks:
      - app_network

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "50052:50052"
    networks:
      - app_network

  composition_service:
    build:
      context: ./composition_service
    volumes:
      - ./score_service:/app/score_service 
      - ./auth_service:/app/auth_service  
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app_network
    depends_on:
      - scoring
      - auth_service

  load_balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - composition_service

networks:
  app_network:
    driver: bridge

