# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x07scoring\"\x1d\n\x0cScoreRequest\x12\r\n\x05login\x18\x01 \x01(\t\"\x1e\n\rScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x32K\n\x0eScoringService\x12\x39\n\x08GetScore\x12\x15.scoring.ScoreRequest\x1a\x16.scoring.ScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=26
  _globals['_SCOREREQUEST']._serialized_end=55
  _globals['_SCORERESPONSE']._serialized_start=57
  _globals['_SCORERESPONSE']._serialized_end=87
  _globals['_SCORINGSERVICE']._serialized_start=89
  _globals['_SCORINGSERVICE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
